"""empty message

Revision ID: 47c0324d5e3a
Revises: 489d6cbc9578
Create Date: 2026-05-14 15:08:59.372443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c0324d5e3a'
down_revision = '489d6cbc9578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_username', sa.String(length=20), nullable=False),
    sa.Column('friend_daily_uniqueness', sa.Integer(), nullable=True),
    sa.Column('friend_all_time_uniqueness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_username'], ['user.username'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
