"""empty message

Revision ID: 489d6cbc9578
Revises: 
Create Date: 2026-05-06 12:03:48.839969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '489d6cbc9578'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(length=100), nullable=False),
    sa.Column('condition_compatibility', sa.String(length=100), nullable=False),
    sa.Column('texture_path', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('conditions',
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_table('game__stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('global_games_played', sa.Integer(), nullable=False),
    sa.Column('lowest_uniqueness', sa.Integer(), nullable=False),
    sa.Column('average_uniqueness', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('block__stats',
    sa.Column('square_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('times_chosen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ),
    sa.PrimaryKeyConstraint('square_id', 'block_id')
    )
    op.create_table('current__game',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('square_id', sa.Integer(), nullable=False),
    sa.Column('uniqueness', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game__stats.game_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_username', sa.String(length=20), nullable=False),
    sa.Column('friend_daily_uniqueness', sa.Integer(), nullable=True),
    sa.Column('friend_all_time_uniqueness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_username'], ['user.username'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_username')
    )
    op.create_table('gameboard',
    sa.Column('square_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('row_condition_id', sa.Integer(), nullable=False),
    sa.Column('column_condition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ),
    sa.ForeignKeyConstraint(['column_condition_id'], ['conditions.condition_id'], ),
    sa.ForeignKeyConstraint(['row_condition_id'], ['conditions.condition_id'], ),
    sa.PrimaryKeyConstraint('square_id', 'block_id')
    )
    op.create_table('inventory',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'block_id')
    )
    op.create_table('personal__stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_games_played', sa.Integer(), nullable=False),
    sa.Column('total_games_won', sa.Integer(), nullable=False),
    sa.Column('lowest_uniqueness', sa.Integer(), nullable=True),
    sa.Column('average_uniqueness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal__stats')
    op.drop_table('inventory')
    op.drop_table('gameboard')
    op.drop_table('friends')
    op.drop_table('current__game')
    op.drop_table('block__stats')
    op.drop_table('user')
    op.drop_table('game__stats')
    op.drop_table('conditions')
    op.drop_table('blocks')
    # ### end Alembic commands ###
