"""empty message

Revision ID: 82346ad28503
Revises: 6ab138156670
Create Date: 2026-05-14 20:41:52.137195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82346ad28503'
down_revision = '6ab138156670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.drop_table('gameboard')
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_texture_path', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('inv_texture_path', sa.String(length=200), nullable=False))
        batch_op.drop_column('texture_path')

    with op.batch_alter_table('current__game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_state', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('puzzle_date', sa.String(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('game_id')
        batch_op.drop_column('square_id')
        batch_op.drop_column('uniqueness')

    with op.batch_alter_table('game__stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reset_date', sa.String(length=10), nullable=True))
        batch_op.alter_column('lowest_uniqueness',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('average_uniqueness',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('personal__stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_uniqueness', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('personal__stats', schema=None) as batch_op:
        batch_op.drop_column('daily_uniqueness')

    with op.batch_alter_table('game__stats', schema=None) as batch_op:
        batch_op.alter_column('average_uniqueness',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('lowest_uniqueness',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('last_reset_date')

    with op.batch_alter_table('current__game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uniqueness', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('square_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'game__stats', ['game_id'], ['game_id'])
        batch_op.drop_column('puzzle_date')
        batch_op.drop_column('board_state')

    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texture_path', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('inv_texture_path')
        batch_op.drop_column('face_texture_path')

    op.create_table('gameboard',
    sa.Column('square_id', sa.INTEGER(), nullable=False),
    sa.Column('block_id', sa.INTEGER(), nullable=False),
    sa.Column('row_condition_id', sa.INTEGER(), nullable=False),
    sa.Column('column_condition_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ),
    sa.ForeignKeyConstraint(['column_condition_id'], ['conditions.condition_id'], ),
    sa.ForeignKeyConstraint(['row_condition_id'], ['conditions.condition_id'], ),
    sa.PrimaryKeyConstraint('square_id', 'block_id')
    )
    op.drop_table('friends_table')
    # ### end Alembic commands ###
