"""empty message

Revision ID: e6d3d94ca58e
Revises: 82346ad28503
Create Date: 2026-05-15 17:35:10.801780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d3d94ca58e'
down_revision = '82346ad28503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(length=100), nullable=False),
    sa.Column('condition_compatibility', sa.String(length=100), nullable=False),
    sa.Column('face_texture_path', sa.String(length=200), nullable=False),
    sa.Column('inv_texture_path', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('conditions',
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_table('game__stats',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('global_games_played', sa.Integer(), nullable=False),
    sa.Column('lowest_uniqueness', sa.Integer(), nullable=True),
    sa.Column('average_uniqueness', sa.Integer(), nullable=True),
    sa.Column('last_reset_date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('block__stats',
    sa.Column('square_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('times_chosen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ),
    sa.PrimaryKeyConstraint('square_id', 'block_id')
    )
    op.create_table('current__game',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('board_state', sa.Text(), nullable=False),
    sa.Column('puzzle_date', sa.String(length=10), nullable=False),
    sa.Column('current_durability', sa.Integer(), nullable=True),
    sa.Column('current_us', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('friends_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('inventory',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'block_id')
    )
    op.create_table('personal__stats',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_games_played', sa.Integer(), nullable=False),
    sa.Column('total_games_won', sa.Integer(), nullable=False),
    sa.Column('lowest_uniqueness', sa.Integer(), nullable=True),
    sa.Column('average_uniqueness', sa.Integer(), nullable=True),
    sa.Column('daily_uniqueness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal__stats')
    op.drop_table('inventory')
    op.drop_table('friends_table')
    op.drop_table('current__game')
    op.drop_table('block__stats')
    op.drop_table('user')
    op.drop_table('game__stats')
    op.drop_table('conditions')
    op.drop_table('blocks')
    # ### end Alembic commands ###
